# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '/'
    weight: 10
  - name: Research
    url: '/research'
    weight: 20
  #- name: Events
  #  url: '/event'
  #  weight: 40
  - name: Publications
    url: '/publication'
    weight: 30
  - name: Awards & Services
    url: '/awards-services'
    weight: 60
  - name: Softwares
    url: '/softwares'
    weight: 40
  - name: Posts
    url: '/post'
    weight: 100
  #- name: Contact
  #  url: '/contact'
  #  weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
